name: Run JMeter Performance Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create reports directory
        run: mkdir -p 'Teste_QA_Performance_Sinqia/report/Smoke'

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: './Teste_QA_Performance_Sinqia/Compra_Passagem_SMOKE.jmx'
          args: "-l ./Teste_QA_Performance_Sinqia/agg/result.jtl -e -o ./Teste_QA_Performance_Sinqia/report/Smoke/"

      - name: List files in agg directory
        run: ls -la ./Teste_QA_Performance_Sinqia/agg/

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: './Teste_QA_Performance_Sinqia/agg/result.jtl'
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-reports
          path: './Teste_QA_Performance_Sinqia/report/Smoke'
          if-no-files-found: error
