name: Run JMeter Performance Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.2
        with:
          # Caminho do arquivo JMX de teste (correto: test-plan-path)
          test-plan-path: 'Teste_QA_Performance_Sinqia/Compra_Passagem_SMOKE.jmx'
          # Caminho para salvar o arquivo de resultados (correto: results-file)
          results-file: 'Teste_QA_Performance_Sinqia/agg/result.jtl'

      - name: Generate HTML report
        run: |
          mkdir -p 'Teste_QA_Performance_Sinqia/report/Smoke'
          jmeter -g 'Teste_QA_Performance_Sinqia/agg/result.jtl' -o 'Teste_QA_Performance_Sinqia/report/Smoke'

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: 'Teste_QA_Performance_Sinqia/report/Smoke'