name: Run JMeter Performance Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          # Caminho do arquivo de teste JMX
          test-plan-path: ./Teste_QA_Performance_Sinqia/Compra_Passagem_SMOKE.jmx
          # Argumentos para gerar o relatório HTML
          args: "-e -o ./Teste_QA_Performance_Sinqia/report/Smoke/"

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          # Caminho do arquivo de resultado JTL
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          # Caminho dos relatórios HTML gerados
          name: jmeter-html-reports
          path: './Teste_QA_Performance_Sinqia/report/Smoke'
          if-no-files-found: error
