name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run JMeter tests
        uses: sebiboga/run-jmeter-github-action@v0.0.5
        with:
          test_files: "Teste_QA_Performance_Sinqia/Compra_Passagem_SMOKE.jmx"
          result_file: "Teste_QA_Performance_Sinqia/agg/result.jtl"

      - name: Generate HTML report
        run: |
          mkdir -p report/html
          jmeter -g "Teste_QA_Performance_Sinqia/agg/result.jtl" -o report/html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: report/html